### ISSUE TITLE
Shows `File Uploaded` message while throwing `IsADirectoryError`

### ISSUE THREAD

**Issue by stsdc** [Carglglz/upydev#10]
I'm using `upydev put -fre src/*`

```shell
Traceback (most recent call last):
  File "/home/stsdc/.local/bin/upytool", line 385, in <module>
    main()
  File "/home/stsdc/.local/bin/upytool", line 379, in main
    put_file(ws, src_file, dst_file)
  File "/home/stsdc/.local/bin/upytool", line 178, in put_file
    with open(local_file, "rb") as f:
IsADirectoryError: [Errno 21] Is a directory: 'src/ble'
File Uploaded!
```

BTW how to upload a folder? My project structure:
```
├── dev-requirements.txt
├── micropy.json
├── pymakr.conf
├── requirements.txt
├── src
│   ├── ble
│   │   ├── ble_advertising.py
│   │   ├── ble.py
│   │   └── ble_temperature.py
│   ├── boot.py
│   └── main.py
└── upydev_.config
```

**Comment by stsdc** [comment]
Fixed uploading nested folder with this: `upydev put -fre src/*/*`

**Comment by Carglglz** [comment]
> BTW how to upload a folder? My project structure:

You could use also **d_sync** mode:

From the README:

> **d_sync**: to recursively sync a folder in upydevice filesystem use -dir to indicate the folder (must be in cwd), use '-tree' to see dir structure, or '-s sd' to sync to an Sd card mounted as 'sd'

See also the Documentation example: [d_sync demo](https://github.com/Carglglz/upydev/blob/master/DOCS/Documentation.md#d_sync)

Also check 'git' integration in SHELLS (SSL/Web/SERIAL) 👍

**Comment by stsdc** [comment]
`d_sync` is cool, but how to put everything in `src` directory to `/` in the board? Because it creates `src` directory on the board as well. Tried `src/*`, but does not work.

**Comment by Carglglz** [comment]
I see now that's why I think I made the git integration and the `git clone_dev`command, but I will check if I can port this to a 'sync_root' mode for example.

**Comment by stsdc** [comment]
it would be then easier to implement `watch` mode. It will just trigger `sync_root`.

**Comment by Carglglz** [comment]
I've just commit a fix for d_sync mode, now if you cd into 'src' and do `$ upydev d_sync -tree` (-tree flag is optional) It will synchronise `src` to `/` as
```
./
├── ble
│   ├── ble_advertising.py
│   ├── ble.py
│   └── ble_temperature.py
├── boot.py
└── main.py
```

**Comment by Carglglz** [comment]
> it would be then easier to implement `watch` mode. It will just trigger `sync_root`.

Yes, but it will need to keep a log somewhere so it doesn't overwrite a file/folder if it hasn't changed ? or how do you would do this?
