### ISSUE TITLE
Dependency `requests` missing

### ISSUE THREAD

**Issue by DrTom** [Carglglz/upydev#2]
I ran into the error: 
```
$ upydev -h
Traceback (most recent call last):
  File "/Users/thomas/Programming/HA/MicroPython/venv/bin/upydev", line 17, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

which was  resolved by: 
`pip install requests`

I am using python 3.7.4 from MacPorts wrapped via `venv` under Mac OS Mojave

**Comment by Carglglz** [comment]
Hi @DrTom 
You are right so I've already updated the repo and requests dependency will be included in the next release.
Thanks for reporting this issue.
