### ISSUE TITLE
SSLWebREPL key generation assumes host network interface is called 'en0' and fails if its not

### ISSUE THREAD

**Issue by chrisb2** [Carglglz/upydev#4]
When generating private key and certs for SSLWebREPL with 
```
upydev sslgen_key -tfkey
```
It failed with:
```
Generating SSL ECDSA key and certificates...
Getting unique id...
ID: 30aea42313e0
Passphrase:
Traceback (most recent call last):
  File "/home/chris/.espressif/python_env/idf3.3_py3.6_env/bin/upydev", line 5147, in <module>
    get_ssl_keycert(args.t, args.p)
  File "/home/chris/.espressif/python_env/idf3.3_py3.6_env/bin/upydev", line 4176, in get_ssl_keycert
    ssl_ECDSA_key_certgen(ip, passwd, dir=upydev.__path__[0]+'/')
  File "/home/chris/.espressif/python_env/idf3.3_py3.6_env/bin/upydev", line 1730, in ssl_ECDSA_key_certgen
    host_ip = netifaces.ifaddresses('en0')[netifaces.AF_INET][0]['addr']
ValueError: You must specify a valid interface name.
```
When looking at [upydev#L1730](https://github.com/Carglglz/upydev/blob/master/upydev_dir/bin/upydev#L1730) I could see it expected network interface of the host to be 'en0', which does not exist in my env (Ubuntu WSL in Windows 10). I edited the file and changed this to a network interface from ifconfig and the key generation and upload then succeeded.

**Comment by chrisb2** [comment]
The assumption of network interface also exists at [sslweb_repl#L160](https://github.com/Carglglz/upydev/blob/master/ssl_web_repl_dir/bin/sslweb_repl#L160) and [sslweb_repl#L541](https://github.com/Carglglz/upydev/blob/master/ssl_web_repl_dir/bin/sslweb_repl#L541) where it prevents:
```
upydev ssl_wrepl
```
from working until its edited to an existing interface.

**Comment by Carglglz** [comment]
Hi @chrisb2 thanks for checking this out.
To be honest you are right , I totally forgot to change it :(.
I've already committed the fix version so it would be nice if you can try it and see if it works as expected before I upload this to PYPI. 
Thanks again for pointing this out 👍

**Comment by chrisb2** [comment]
Tested as follows:
1. Uninstalled existing version using pip
2. Installed latest from github using: pip install https://github.com/Carglglz/upydev.git
3. Ran: upydev sslgen_key -tfkey
4. Ran: upydev ssl_wrepl

All working - thanks for the quick fix and your excellent library!

Chris

**Comment by Carglglz** [comment]
You're welcome! and thanks again for reporting the issue.
