### ISSUE TITLE
Shows file uploaded, even there an error occurred

### ISSUE THREAD

**Issue by stsdc** [Carglglz/upydev#8]
```shell
Uploading file main.py...
op:put, host:192.168.1.102, port:8266, passwd:****.
src/main.py -> /main.py
Traceback (most recent call last):
  File "/home/stsdc/.local/bin/upytool", line 385, in <module>
    main()
  File "/home/stsdc/.local/bin/upytool", line 363, in main
    s.connect(addr)
ConnectionRefusedError: [Errno 111] Connection refused
File Uploaded!
```

**Comment by Carglglz** [comment]
Thanks for reporting this, I've just commit a quick fix for this issue. 
Also check [DEBUG](https://github.com/Carglglz/upydev/blob/master/README.md/#how-to) in *How to* section of the README in case you find any further issues, it may be of help. 

For the `ConnectionRefusedError: [Errno 111] Connection refused` check if the the device is accessible with `$ upydev ping` or `$ upydev find -n 3` and then `$ upydev wrepl` to see if WebREPL is operative. 

Also be aware that a `while` loop in the  device *main.py* script could block WebREPL access.

**Comment by stsdc** [comment]
Yes, thank you. I did already found out, that I commented out `webrepl.start()` :grimacing:
